create table customer(
customerid number generated by default on null as identity primary key,
customername varchar2(100),
address varchar(200),
city varchar(100),
state varchar(100),
zip NUMBER
);

create table accounts(
accountid number generated by default on null as identity primary key,
customerid number,
accountnumber number,
dateopened varchar2(100),
dateclosed varchar2(100),
accounttype varchar2(100),
balance NUMBER(10,2),
foreign key (customerid) references customer(customerid)
);

drop table transactions;
drop table accounts;

create table transactions(
transactionid number generated by default as identity primary key,
accountid number,
transactiondate varchar2(100),
amount NUMBER(10,2),
transactiontype varchar(100),
foreign key (accountid) references accounts(accountid)
);

select * from customer;
select * from accounts;
select * from transactions;

desc customer;
desc accounts;
desc transactions;


-------------------------
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Dexter','nisi.','sed,','LR','15976');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Jackson','tempor,','adipiscing,','VII','31813');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Wynter','felis,','feugiat','NI','38592');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Imani','mauris','ante.','Leinster','52871');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Leila','Fusce','in,','Ontario','82329');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Dora','Aenean','eros.','HB','90336');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Ethan','ornare','erat','U','95044');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Indira','ultricies','lobortis','Connacht','80497');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Isabelle','feugiat','Maecenas','MA','50247');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Sharon','diam','justo','PUG','84450');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kane','nisi','auctor','Mazowieckie','12668');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Aladdin','Quisque','eget','WP','99042');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Travis','ultricies','pede','C','31045');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Grace','eget','lacinia','HI','93513');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kameko','dignissim','consectetuer,','OS','71110');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Maile','odio.','ridiculus','Araucanía','37230');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Mufutau','interdum','suscipit','SI','25822');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Pascale','elit,','a','Delaware','75191');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Zia','convallis','commodo','VII','33029');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kylee','tellus.','diam','IN','11620');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Emerald','In','justo','Provence-Alpes-Côte d''Azur','62735');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Ali','pharetra','blandit.','Zl','21392');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Hasad','ac','nec,','Västra Götalands län','91432');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Tara','eu','facilisis','Bremen','37288');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Aquila','urna.','mauris.','KO','69157');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Shelly','Proin','ligula.','Wie','14012');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Irene','sagittis','nulla.','Quebec','47713');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Deborah','dis','viverra.','Tyrol','71673');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Stuart','tellus','justo','Ulster','01776');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Colette','eu','auctor','Istanbul','82616');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Burton','Donec','massa.','Noord Brabant','97437');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Leigh','magna.','gravida.','Sardegna','10868');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Buckminster','dui.','neque','Manitoba','78085');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Brynne','quis','ipsum','PK','18199');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Olga','magnis','egestas','Kah','16937');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Xander','Cras','Phasellus','NI','64395');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Dorian','Donec','in','Wielkopolskie','03590');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Bevis','Aliquam','Nunc','Cartago','11370');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Colleen','Nunc','elementum','Madrid','16444');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Orson','id,','mollis','Västra Götalands län','16222');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Adrienne','dictum','cursus,','AB','86119');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kaye','sed,','nunc.','Şanlıurfa','72597');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Felix','gravida','enim.','BE','02732');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Leo','Maecenas','et,','WM','51466');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Jada','magna.','et,','Antofagasta','24925');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Suki','lacinia.','Nullam','Kon','82789');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Beck','tellus.','mollis','Clackmannanshire','51394');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Emma','nibh.','neque','North Island','91604');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Genevieve','orci','ipsum.','New South Wales','94251');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Elmo','Curabitur','aliquet','NE','68890');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Fritz','in,','amet','UMB','63157');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Callie','Nam','iaculis','MD','31854');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Brody','egestas.','tempor','Rio de Janeiro','20514');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Demetrius','congue','semper','Luxemburg','29474');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Shad','malesuada','venenatis','Ontario','59390');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Candice','sociis','Nunc','Jharkhand','63735');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Stacey','fames','eu','Samsun','27188');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kaye','aliquet','pede.','Vermont','60213');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Nerea','risus.','lacus.','Imo','31723');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Tasha','massa.','scelerisque','WV','36273');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Quail','tristique','quam.','BE','04555');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Ayanna','Donec','Sed','NT','14174');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Rhoda','In','ante.','OH','62668');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Quemby','placerat','eleifend.','Atacama','70836');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Conan','enim','lacinia','ON','66609');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Madonna','tortor,','nonummy','NA','05226');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Colette','amet,','scelerisque','Quebec','36743');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Omar','est','Fusce','Alberta','19073');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Jared','tincidunt','magna.','NA','69495');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kasper','dui,','egestas.','Bourgogne','36591');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Reed','faucibus.','fringilla,','N.','82405');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Cain','sem.','vulputate,','Rio Grande do Sul','96513');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Cairo','luctus','pellentesque,','Z.','51867');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Hu','tincidunt,','ante','SIC','04395');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Hoyt','Quisque','Nunc','QC','16310');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Riley','Nunc','sodales.','RS','67407');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Anastasia','vulputate,','non,','Metropolitana de Santiago','49399');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Ivory','vulputate,','primis','Aberdeenshire','68197');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Todd','Sed','penatibus','Queensland','74941');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Oleg','molestie','tincidunt','Koc','60822');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Raymond','quis,','consectetuer','OY','78809');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Joy','adipiscing','nec,','Overijssel','71742');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Mariko','aliquam','a','Berlin','49459');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Graiden','ligula','mattis.','Ontario','79500');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Veda','consectetuer,','arcu.','Ontario','79862');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Hadley','et,','vulputate,','Uttar Pradesh','54942');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Brett','arcu','magna.','Ontario','28472');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Jacqueline','natoque','enim','AN','20217');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Fulton','nunc','lobortis','L.','86089');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Scott','dis','purus.','Saskatchewan','89139');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Callum','ipsum.','vulputate,','Sicilia','18123');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Burton','nonummy.','pellentesque,','Washington','16791');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('India','eget','arcu','LI','87094');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Regan','posuere','amet','NW','65644');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Kay','Phasellus','a,','V','19034');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Constance','Aliquam','aliquam','SP','23944');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Colorado','auctor,','lacus.','PM','15861');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Diana','nisi','sit','BE','18682');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Marny','sed','nunc','Istanbul','14938');
INSERT INTO Customer (Customername,Address,city,state,zip) VALUES ('Karina','vulputate','eget','ON','34477');
select * from customer;


------------------

desc accounts;

INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (1,5063,'03/08/15','04/10/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (2,9247,'06/14/15','06/21/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (3,9201,'09/16/15','01/15/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (4,2112,'09/01/15','09/29/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (5,4170,'12/23/14','05/15/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (6,4032,'03/03/15','03/05/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (7,5602,'01/10/15','10/07/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (8,7214,'08/11/15','02/18/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (9,9461,'01/04/15','03/29/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (10,4447,'12/19/14','05/14/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (11,3371,'02/18/15','02/29/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (12,2263,'04/05/15','03/25/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (13,1060,'05/27/15','10/21/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (14,4058,'01/28/15','05/15/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (15,6913,'01/24/15','08/07/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (16,9251,'01/06/15','09/01/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (17,1454,'11/09/14','01/23/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (18,3889,'04/20/15','06/10/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (19,8217,'02/26/15','10/01/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (20,4911,'10/12/14','11/28/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (21,7687,'12/13/14','07/29/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (22,2861,'05/16/15','06/04/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (23,9685,'05/30/15','01/01/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (24,8443,'12/03/14','04/16/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (25,2396,'12/26/14','07/20/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (26,7551,'06/16/15','07/11/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (27,7174,'09/19/15','07/30/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (28,7785,'04/14/15','01/25/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (29,9395,'01/28/15','07/09/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (30,3716,'04/08/15','06/11/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (31,1957,'09/17/15','03/30/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (32,7526,'10/23/14','05/21/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (33,2123,'08/17/15','03/05/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (34,7683,'07/30/15','07/31/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (35,8329,'08/11/15','02/08/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (36,5064,'03/20/15','05/21/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (37,5380,'09/10/15','04/15/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (38,2184,'10/31/14','04/04/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (39,5353,'08/13/15','04/13/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (40,1534,'12/07/14','06/27/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (41,7162,'08/11/15','01/08/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (42,6766,'01/21/15','10/31/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (43,2498,'01/12/15','08/21/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (44,7953,'04/14/15','10/21/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (45,9401,'08/20/15','04/17/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (46,4514,'10/19/14','03/09/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (47,9905,'01/30/15','08/25/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (48,6720,'08/07/15','03/15/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (49,2475,'01/18/15','11/29/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (50,2939,'02/11/15','02/29/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (51,3518,'09/19/15','04/23/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (52,4241,'02/21/15','01/10/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (53,4060,'07/22/15','12/30/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (54,7040,'08/13/15','10/10/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (55,2599,'03/07/15','05/01/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (56,8780,'01/06/15','01/31/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (57,7743,'08/09/15','11/01/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (58,9055,'12/04/14','02/26/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (59,5244,'05/02/15','04/15/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (60,9860,'12/01/14','06/13/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (61,6398,'02/18/15','01/07/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (62,6873,'05/20/15','04/03/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (63,9433,'10/08/14','10/22/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (64,7035,'04/18/15','04/26/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (65,4365,'01/01/15','11/10/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (66,3452,'11/26/14','11/26/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (67,3634,'10/07/14','11/26/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (68,3327,'02/14/15','09/07/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (69,2780,'11/22/14','11/08/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (70,9243,'05/31/15','02/18/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (71,8524,'03/15/15','09/25/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (72,7310,'07/10/15','09/05/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (73,8536,'10/11/14','03/13/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (74,1053,'07/30/15','04/04/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (75,7535,'03/31/15','12/17/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (76,1508,'06/25/15','04/26/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (77,5806,'02/26/15','09/25/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (78,5999,'11/30/14','04/03/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (79,3354,'02/22/15','05/15/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (80,2222,'06/14/15','12/06/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (81,4582,'11/20/14','09/25/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (82,6500,'02/19/15','04/28/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (83,7311,'04/18/15','09/05/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (84,9231,'07/05/15','10/22/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (85,9669,'01/20/15','02/29/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (86,2358,'07/07/15','09/29/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (87,8544,'01/24/15','11/12/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (88,7741,'06/17/15','09/20/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (89,1304,'02/21/15','06/08/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (90,2689,'01/25/15','04/03/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (91,1437,'03/23/15','10/25/15','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (92,7124,'09/03/15','05/25/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (93,9208,'02/20/15','11/19/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (94,1088,'03/03/15','02/11/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (95,3103,'08/27/15','11/01/15','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (96,4112,'08/16/15','01/22/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (97,3558,'12/16/14','09/13/16','checking');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (98,9929,'06/09/15','02/03/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (99,5895,'05/09/15','01/13/16','saving');
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype) VALUES (100,9453,'03/17/15','03/28/16','checking');

desc accounts;
-----------------

select * from accounts;

------------
desc transactions;


INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (1,'06/27/16',947,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (2,'01/15/16',944,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (3,'04/09/16',254,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (4,'08/31/16',125,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (5,'08/18/16',450,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (6,'06/09/16',254,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (7,'09/20/16',437,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (8,'07/18/16',317,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (9,'04/03/16',871,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (10,'06/13/16',380,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (11,'08/19/16',566,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (12,'12/20/15',599,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (13,'05/03/16',639,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (14,'09/15/16',561,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (15,'03/03/16',318,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (16,'05/18/16',663,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (17,'08/03/16',779,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (18,'11/07/15',876,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (19,'08/27/16',538,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (20,'01/03/16',157,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (21,'12/31/15',795,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (22,'06/08/16',464,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (23,'10/05/16',534,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (24,'06/07/16',113,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (25,'11/16/15',619,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (26,'04/19/16',254,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (27,'04/11/16',293,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (28,'11/21/15',879,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (29,'12/30/15',508,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (30,'10/31/15',162,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (31,'04/11/16',191,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (32,'07/06/16',525,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (33,'11/22/15',690,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (34,'07/15/16',898,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (35,'03/08/16',201,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (36,'09/01/16',553,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (37,'04/14/16',513,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (38,'01/16/16',483,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (39,'06/27/16',822,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (40,'03/27/16',548,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (41,'08/31/16',186,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (42,'07/27/16',622,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (43,'10/28/15',622,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (44,'10/04/16',690,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (45,'02/11/16',380,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (46,'10/18/15',674,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (47,'03/22/16',659,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (48,'05/04/16',537,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (49,'10/02/16',920,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (50,'12/17/15',508,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (51,'12/29/15',108,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (52,'09/14/16',493,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (53,'09/19/16',208,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (54,'04/14/16',574,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (55,'03/25/16',738,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (56,'05/24/16',638,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (57,'02/10/16',908,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (58,'09/17/16',860,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (59,'03/31/16',213,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (60,'10/26/15',287,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (61,'11/04/15',103,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (62,'10/14/15',487,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (63,'01/04/16',241,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (64,'03/14/16',912,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (65,'09/13/16',701,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (66,'08/04/16',215,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (67,'08/17/16',591,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (68,'08/28/16',189,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (69,'04/07/16',358,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (70,'08/30/16',535,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (71,'04/03/16',103,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (72,'01/01/16',285,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (73,'11/30/15',396,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (74,'07/06/16',323,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (75,'06/20/16',533,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (76,'07/22/16',627,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (77,'08/13/16',674,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (78,'09/20/16',219,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (79,'10/01/16',133,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (80,'10/07/15',929,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (81,'07/16/16',966,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (82,'10/24/15',418,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (83,'09/09/16',203,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (84,'11/17/15',575,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (85,'07/25/16',154,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (86,'01/20/16',623,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (87,'10/07/15',740,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (88,'09/05/16',328,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (89,'08/09/16',960,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (90,'01/06/16',385,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (91,'09/07/16',927,'savingswithdraw ');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (92,'12/06/15',543,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (93,'08/21/16',975,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (94,'10/29/15',170,'checkwithdraw');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (95,'12/22/15',881,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (96,'06/18/16',895,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (97,'05/09/16',157,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (98,'06/15/16',457,'bankfee');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (99,'05/01/16',972,'deposit');
INSERT INTO transactions (accountid,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE) VALUES (100,'04/16/16',708,'checkwithdraw');

select * from transactions;

select count(*) from transactions where TRANSACTIONTYPE like '%withdraw%' or TRANSACTIONTYPE like '%fee%' ;
select count(*) from transactions u where u.transactiontype = 'checkwithdraw' OR u.transactiontype = 'bankfee' OR u.transactiontype = 'savingswithdraw';

drop table transactions;
drop table accounts;

INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (1,4763,'07/06/14','11/27/15','checking',4899);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (2,2979,'10/07/13','12/24/15','checking',6520);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (3,3774,'07/13/14','08/01/17','saving',5197);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (4,3216,'09/30/14','07/24/16','saving',1325);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (5,1452,'06/06/14','02/12/16','checking',4961);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (6,3316,'11/22/13','06/17/16','saving',5372);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (7,3650,'04/19/14','04/22/16','checking',2312);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (8,4399,'12/14/13','12/14/16','saving',7614);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (9,6810,'02/18/14','03/03/16','saving',6364);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (10,3487,'02/02/14','11/15/15','checking',7735);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (11,9409,'11/12/13','12/23/15','saving',854);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (12,8653,'02/10/14','07/04/16','checking',9208);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (13,4247,'01/30/14','03/16/17','saving',3423);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (14,6721,'08/17/14','07/14/17','saving',1099);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (15,9152,'02/14/14','06/04/16','saving',8223);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (16,5707,'03/30/14','09/10/17','checking',2760);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (17,5698,'03/05/14','04/07/16','checking',5869);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (18,6400,'12/26/13','12/07/15','saving',6919);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (19,5272,'09/05/14','10/18/16','checking',9942);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (20,3262,'10/16/13','03/22/17','checking',7851);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (21,3904,'08/27/14','01/03/16','checking',3856);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (22,6219,'12/07/13','03/16/17','checking',1068);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (23,8989,'05/23/14','08/21/16','checking',3728);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (24,2514,'03/03/14','04/27/16','checking',7467);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (25,1943,'07/05/14','07/29/17','saving',9864);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (26,7706,'09/23/14','10/10/15','checking',4981);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (27,9963,'11/26/13','05/30/17','saving',4849);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (28,4674,'12/30/13','01/21/16','checking',7296);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (29,2654,'04/17/14','01/25/16','checking',8579);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (30,8625,'12/08/13','01/13/16','saving',4355);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (31,6384,'05/11/14','07/13/16','checking',1434);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (32,7584,'08/06/14','05/19/17','checking',1675);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (33,6577,'11/03/13','02/11/17','saving',3949);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (34,9953,'11/08/13','01/24/16','checking',2166);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (35,9561,'08/27/14','07/27/17','saving',9475);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (36,5154,'12/21/13','08/19/16','checking',6649);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (37,8053,'08/13/14','05/21/17','saving',6547);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (38,3432,'08/10/14','03/10/16','checking',881);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (39,5724,'12/07/13','06/19/16','saving',4983);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (40,9476,'04/12/14','08/08/17','saving',8020);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (41,1010,'03/01/14','07/16/16','checking',6121);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (42,6789,'10/26/13','02/16/17','saving',3602);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (43,7058,'10/05/14','09/08/17','checking',5105);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (44,8719,'11/08/13','04/21/17','checking',1139);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (45,4332,'02/24/14','07/21/17','checking',3710);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (46,5666,'04/16/14','03/18/17','saving',6312);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (47,7416,'04/24/14','07/14/17','checking',4182);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (48,7807,'06/26/14','03/21/17','checking',6772);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (49,8559,'01/16/14','11/02/16','saving',7172);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (50,1066,'10/12/13','10/12/15','checking',4311);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (51,9307,'04/15/14','03/26/17','saving',4886);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (52,7410,'06/20/14','08/22/16','saving',1394);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (53,4051,'08/06/14','11/28/15','saving',6478);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (54,5420,'06/27/14','11/15/15','checking',7709);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (55,1717,'10/05/14','10/18/16','checking',4114);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (56,8656,'02/09/14','01/29/17','checking',5837);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (57,3479,'12/15/13','10/24/15','saving',9524);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (58,6351,'08/10/14','03/16/17','checking',6383);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (59,2517,'02/04/14','08/13/17','saving',7171);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (60,1290,'11/28/13','04/05/16','saving',5851);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (61,8421,'09/29/14','05/13/16','checking',4748);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (62,3132,'12/03/13','01/20/17','checking',499);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (63,6155,'07/09/14','06/05/17','checking',8274);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (64,3389,'02/15/14','01/14/17','saving',9405);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (65,2843,'01/01/14','02/24/16','checking',1612);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (66,7049,'04/11/14','08/06/17','checking',6999);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (67,6018,'04/08/14','11/24/16','saving',5939);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (68,7632,'04/22/14','05/22/17','checking',1960);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (69,9792,'12/28/13','02/04/17','saving',9787);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (70,3789,'04/24/14','11/01/15','saving',4830);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (71,8180,'05/23/14','10/19/15','checking',3958);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (72,7141,'05/13/14','02/15/16','saving',7888);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (73,3506,'06/30/14','07/02/17','checking',9676);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (74,3954,'11/17/13','01/25/16','checking',553);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (75,8406,'08/02/14','06/07/16','checking',2382);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (76,7217,'04/19/14','07/22/16','saving',2456);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (77,1691,'04/01/14','08/15/16','saving',4322);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (78,7592,'02/09/14','02/03/16','saving',7534);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (79,5029,'10/12/13','06/09/16','checking',8079);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (80,7171,'03/14/14','12/11/16','saving',6563);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (81,4946,'03/08/14','06/05/17','saving',7309);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (82,3877,'08/31/14','07/16/16','saving',8125);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (83,1635,'03/26/14','06/16/16','saving',7825);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (84,3419,'10/03/14','04/01/16','saving',6350);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (85,8624,'10/29/13','03/17/16','checking',2135);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (86,2390,'08/22/14','02/02/16','checking',2968);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (87,8004,'10/12/13','02/02/17','checking',887);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (88,6394,'09/13/14','02/15/17','saving',6005);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (89,6584,'01/03/14','04/19/17','checking',5576);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (90,6727,'10/18/13','09/11/17','saving',2948);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (91,1531,'11/15/13','04/07/17','saving',3630);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (92,6347,'12/28/13','03/07/16','saving',1645);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (93,2781,'04/06/14','08/11/17','checking',8700);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (94,5922,'05/14/14','11/30/15','saving',568);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (95,9657,'05/28/14','06/11/16','checking',7180);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (96,3186,'07/07/14','01/17/17','saving',5300);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (97,4475,'09/22/14','02/18/16','saving',4984);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (98,9239,'02/19/14','07/31/16','checking',7952);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (99,6177,'11/04/13','07/26/16','saving',6182);
INSERT INTO Accounts (customerid,Accountnumber,Dateopened,dateclosed,accounttype,balance) VALUES (100,7939,'07/04/14','03/02/16','checking',7508);

desc customer;
select cus.customername, cus.address, cus.city, cus.state, cus.zip, count(acc.accountid) , sum(acc.balance) from customer cus left join accounts acc on cus.customerid = acc.CUSTOMERID group by cus.customername,cus.customername, cus.address, cus.city, cus.state, cus.zip;

select * from accounts;
select * from transactions;
select acc.accountnumber, cus.customername, acc.BALANCE, count(tra.transactionid) from accounts  acc 
left join customer cus on acc.customerid = cus.CUSTOMERID  
left join transactions tra on tra.accountid = acc.ACCOUNTID WHERE acc.ACCOUNTTYPE = 'saving' group by acc.accountnumber, cus.CUSTOMERNAME, acc.balance;
